##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xams/public_html/
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R libs $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp films.css $DEPLOYPATH
    - /bin/cp films.html $DEPLOYPATH
